"""Connect the generated Chisel AXI ports without modifying generated RTL."""

import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
rtl = (root / "generated/PebbleA7Chip.sv").read_text()
header = rtl.split("module PebbleA7Chip(", 1)[1].split(");", 1)[0]
ports = {}
width = ""
for line in header.splitlines():
    line = line.strip().rstrip(",")
    if not line:
        continue
    match = re.match(r"(input|output)\s+(\[[^]]+\])?\s*(\w+)$", line)
    if match:
        direction, width, name = match.groups()
        width = width or ""
    else:
        name = line
    assert re.fullmatch(r"\w+", name), line
    ports[name] = width
lines = ["""// Platform written for Arty A7; generated by scripts/make_platform.py.
module pebble_a7_platform #(
  parameter integer UART_DIVISOR=434,
  parameter INIT_FILE="firmware/demo.hex"
) (
  input wire clk, reset, boot_demo, uart_rx_in,
  output wire uart_tx_out, cpu_run, exited, loader_error,
  output wire [31:0] exit_code
);
  reg demo_run;
  always @(posedge clk) if(reset) demo_run<=boot_demo;
  wire loader_run;
  assign cpu_run = demo_run | loader_run;
  wire cpu_reset = reset | !cpu_run;
  wire rx_valid, rx_error, tx_ready, loader_tx_valid, mmio_tx_valid;
  wire [7:0] rx_data, loader_tx_data, mmio_tx_data;
  wire load_en, load_valid;
  wire [16:0] load_addr;
  wire [127:0] load_data, load_result;
  wire [15:0] load_mask;
  uart_rx #(.DIVISOR(UART_DIVISOR)) receiver (
    .clk(clk),.reset(reset),.rx(uart_rx_in),.valid(rx_valid),.data(rx_data),.frame_error(rx_error));
  uart_tx #(.DIVISOR(UART_DIVISOR)) transmitter (
    .clk(clk),.reset(reset),.valid(cpu_run ? mmio_tx_valid : loader_tx_valid),
    .data(cpu_run ? mmio_tx_data : loader_tx_data),.ready(tx_ready),.tx(uart_tx_out));
  uart_loader loader (
    .clk(clk),.reset(reset | demo_run),.rx_valid(rx_valid && !cpu_run),.rx_data(rx_data),
    .rx_error(rx_error),.tx_valid(loader_tx_valid),.tx_data(loader_tx_data),.tx_ready(tx_ready),
    .cpu_run(loader_run),.error_seen(loader_error),.load_en(load_en),.load_addr(load_addr),
    .load_data(load_data),.load_mask(load_mask),.load_valid(load_valid),.load_result(load_result));
"""]
for name, width in ports.items():
    if name not in ("clock", "reset"):
        lines.append(f"  wire {width} {name};")
connections = {"clock": "clk", "reset": "cpu_reset"}
lines.append(
    "  PebbleA7Chip chip (\n"
    + ",\n".join(f"    .{n}({connections.get(n, n)})" for n in ports)
    + "\n  );"
)
fields = {
    "aw": ["id", "addr", "len", "size", "burst"],
    "w": ["data", "strb", "last"],
    "b": ["id", "resp"],
    "ar": ["id", "addr", "len", "size", "burst"],
    "r": ["id", "data", "resp", "last"],
}
for prefix, instance in [
    ("memory", "axi_bram #(.INIT_FILE(INIT_FILE)) memory_controller"),
    ("peripherals", "axi_uart #(.ADDR_WIDTH(31)) peripheral_controller"),
]:
    pairs = [".clk(clk)", f".reset({'reset' if prefix == 'memory' else 'cpu_reset'})"]
    for channel, names in fields.items():
        for field in names:
            pairs.append(f".{channel}{field}({prefix}_{channel}_bits_{field})")
        for handshake in ["valid", "ready"]:
            pairs.append(f".{channel}{handshake}({prefix}_{channel}_{handshake})")
    if prefix == "memory":
        pairs += [".run(cpu_run)"] + [
            f".{n}({n})"
            for n in [
                "load_en",
                "load_addr",
                "load_data",
                "load_mask",
                "load_valid",
                "load_result",
            ]
        ]
    else:
        pairs += [
            ".rx_valid(rx_valid && cpu_run)",
            ".rx_data(rx_data)",
            ".rx_error(rx_error)",
            ".tx_valid(mmio_tx_valid)",
            ".tx_data(mmio_tx_data)",
            ".tx_ready(tx_ready)",
            ".exited(exited)",
            ".exit_code(exit_code)",
        ]
    lines.append(f"  {instance} (\n    " + ",\n    ".join(pairs) + "\n  );")
lines.append("endmodule\n")
(root / "board/pebble_a7_platform.sv").write_text("\n".join(lines))
print(f"Connected {len(ports)} generated ports; ignored AXI cache/prot/qos/lock hints.")
